version: "3.8"

services:
  mariadb-tde:
    image: mariadb:11.2 # LTS 버전 사용
    container_name: mariadb_tde_demo
    environment:
      MARIADB_ROOT_PASSWORD: rootPassword
      MARIADB_DATABASE: demoDB
      MARIADB_USER: demoUser
      MARIADB_PASSWORD: 1234
      TZ: Asia/Seoul
    volumes:
      # TDE 설정 파일 마운트
      - ./config/my.cnf:/etc/mysql/conf.d/encryption.cnf:ro
      # 암호화 키 폴더 마운트
      - ./keys:/etc/mysql/encryption
      # 데이터 영구 저장
      - ./data:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always
